name: reed_solomon
version: 0.0.8
description: Reed Solomon implementation in pure Dart
author: Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Kleak/reed_solomon

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  galois_field: 0.0.7
