name: reed_solomon
version: 0.0.1
description: Reed Solomon implementation in pure Dart
author: <Kevin Segaud> <segaud.kevin@gmail.com>
homepage: http://www.rollercops.fr/

environment:
  sdk: '>=1.0.0 <2.0.0'
